
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ntsako
 */
public class Pdetails extends javax.swing.JFrame {

    /**
     * Creates new form Pdetails
     */
    public Pdetails() {
        initComponents();
    }
private void clear(){
      DefaultTableModel table = (DefaultTableModel)jTable2.getModel();
        table.setRowCount(0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NTextfield = new javax.swing.JTextField();
        STextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Insertbtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        Viewbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Surname");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Destination");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Contact");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Last Name", "Destination", "Phone"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        Insertbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Insertbtn.setText("Insert");
        Insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertbtnActionPerformed(evt);
            }
        });

        Exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        Viewbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Viewbtn.setText("View");
        Viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbtnActionPerformed(evt);
            }
        });

        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });

        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Insertbtn)
                            .addGap(18, 18, 18)
                            .addComponent(Updatebtn)
                            .addGap(15, 15, 15)
                            .addComponent(Viewbtn)
                            .addGap(13, 13, 13)
                            .addComponent(Deletebtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Exitbtn))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NTextfield)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(STextField)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))))
                .addGap(93, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(NTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(STextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertbtn)
                    .addComponent(Exitbtn)
                    .addComponent(Viewbtn)
                    .addComponent(Updatebtn)
                    .addComponent(Deletebtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void InsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertbtnActionPerformed
     
        try {
                      
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fa3_assessment", "root", "Boitekong2003");
            
            String sql = "INSERT INTO passenger_details(First_Name, Last_Name, Destination, Contact_Details) VALUES(?, ?, ?, ?)";
            PreparedStatement pt= con.prepareCall(sql);
            pt.setString(1, NTextfield.getText());
            pt.setString(2, STextField.getText());
            pt.setString(3, jTextField1.getText());
            pt.setString(4, jTextField2.getText());
          
            
            pt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully inserted the data to the database");
            if(NTextfield.getText().isEmpty() ||
             STextField.getText().isEmpty() ||
            jTextField1.getText().isEmpty() ||
           jTextField2.getText().isEmpty()); {    JOptionPane.showMessageDialog(null, "InputField Empty");
         return;}
        } catch (Exception ex) {
        if (((SQLException) ex).getErrorCode()==1062) {
//JOptionPane.showMessageDialog(null,"Duplicate Entry");
}else {
      JOptionPane.showMessageDialog(null, "SQL Error "+ex.getMessage());      
        }
    }//GEN-LAST:event_InsertbtnActionPerformed
}
    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void ViewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbtnActionPerformed
      clear();
            
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fa3_assessment", "root", "Boitekong2003");
        
        Statement stm = con.createStatement();
        String  sql = "SELECT * FROM passenger_details";
        ResultSet result = stm.executeQuery(sql);
        
        while(result.next()){
            String name = result.getString("First_Name");
               String surname = result.getString("Last_Name");
                  String destination = result.getString("Destination");
                     String phone = result.getString("Contact_Details");
                     String tableData[] ={name, surname, destination, phone};
                     DefaultTableModel table = (DefaultTableModel)jTable2.getModel();
                     table.addRow(tableData);
                     
        }
        
        
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex); 
        }
    }//GEN-LAST:event_ViewbtnActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
              java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fa3_assessment", "root", "Boitekong2003");
              String SQL = "UPDATE passenger_details SET First_Name = ?, Last_Name = ?, Destination = ?, Contact_Details = ?";
              
               PreparedStatement STATE = con.prepareStatement(SQL);
                STATE.setString(1, NTextfield.getText());
            STATE.setString(2, STextField.getText());
            STATE.setString(3, jTextField1.getText());
            STATE.setString(4, jTextField2.getText());
            
              int rowsUpdated = STATE.executeUpdate();
            if (rowsUpdated > 0) {
                
                   JOptionPane.showMessageDialog(null,"Update successful");
            } else {
                
                JOptionPane.showMessageDialog(null,"Update failed");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pdetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pdetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
      
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fa3_assessment", "root", "Boitekong2003");
             
             
            String sql="delete from passenger_details where First_Name=?";
            PreparedStatement State=con.prepareStatement(sql);
             State.setString(1, NTextfield.getText());
            
            State.executeUpdate();
        JOptionPane.showMessageDialog(null, "Successfully Deleted");}
catch (Exception e) {
        if (((SQLException) e).getErrorCode()==1062) {
JOptionPane.showMessageDialog(null,"file already deleted");
}else {
      JOptionPane.showMessageDialog(null, "SQL Error "+e.getMessage());      
        }
        }
            
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
    DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
           int row = jTable2.rowAtPoint(evt.getPoint());
       
        int rows = jTable2.getSelectedRowCount();

        if (rows == 1) {
       
        
        NTextfield.setText(model.getValueAt(row, 0).toString());
          STextField.setText(model.getValueAt(row, 1).toString());
          jTextField1.setText(model.getValueAt(row, 2).toString());
          jTextField2.setText(model.getValueAt(row, 3).toString());
          
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Insertbtn;
    private javax.swing.JTextField NTextfield;
    private javax.swing.JTextField STextField;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JButton Viewbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
